### ISSUE TITLE
Add ShipContext to /app

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#1104]
### Details
We are passing the ship object around constantly using `useServices` and what we really need is a simpler way to load ship metadata (patp, nickname, avatar, sigilColor)

### Tasks
- [ ] add current ship to `window.ship` 
- [ ] Investigate whether adding a new `useShip` hook is necessary
- [ ] If necessary, implement `useShip` hook
