### ISSUE TITLE
Initial mic capture not working for everyone

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#1105]
### Details

Sometimes when people first use Realm, the approve mic permission prompt is triggered while the WebRTC connections are trying to setup media streams. If a user doesn't approve fast enough, they get into an odd state. 

### Todo
- [ ] Design the permission check element @drunkplato 
- [ ] When rooms tray is first opened, show a UI element asking to click to give permission, prompt for mic permission, forcing the user to approve or deny mic perms. 
  - Linux skips this check 
- [ ] If they click deny, disable the rooms tray until it is enabled in settings
