### ISSUE TITLE
Handle OTAs in Realm settings

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#1106]
### Details

Currently, to deal with OTAs users have to open landscape. Instead, we will allow users to manage OTA sources, apply OTAs on demand and notify them of new OTAs.

We should allow users to manually trigger OTAs with an "Update Now". Else, it will be within the maintenance window they have scheduled.

### Todo
- [ ] Design Urbit OTA section in Settings @drunkplato
- [ ] Design OTA notification @drunkplato
- [ ] Build `/os` service called `ota.service.ts`.
  - [ ] `onUpdateStatus` preload callback. Should have these statuses.
    - [ ] `update-available` 
    - [ ] `update-started`
    - [ ] `update-completed`
- [ ] OTAs should have their own notification (integrated with `notif-db`) that is pinned to the top of the Notification tray until handled.
