### ISSUE TITLE
Pin / unpin chats via %realm-chat

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#1114]
### Details

We need the ability to pin and unpin chats. This should be stored in `%realm-chat` with a simple poke and update. 

### Todo
- [ ] Design pinned list view @drunkplato 
- [x] Implement pin/unpin poke and update @Tenari 
- [ ] Implement in desktop @drunkplato
