### ISSUE TITLE
Consolidate all desks into %realm

### ISSUE THREAD

**Issue by ajlamarc** [holium/realm#1157]
Managing 4-5 separate desks, and more in the future, will introduce overhead and issues with linking dependencies.  

- Distributing a Realm developer ship will become more complicated, as we will need to repeatedly add those new desks to it.
- Opening landscape will have N useless tiles instead of 1.
- Won't have to hide new desks from our apps page as they are created.

**Goal:** Booting into Realm should only require `%base` and `%realm`.  Users should not need `%garden` or other Tlon desks to function.

For libraries that we are _not_ managing, they should be symlinked into the repository to avoid becoming stale.

**TODOs**
- [ ] Move all agents and libraries into %realm, creating subfolders as needed
- [ ] Remove frontend references to `%courier`, `%usher`, `%realm-chat`, `%chat-db`, `%notif-db`
- [ ] Fix relevant CI/CD deployment pipelines
- [ ] Create symlinks to dependencies in `%garden`
- [ ] Test booting a ship with only `%base` and `%realm` and go through onboarding

Edit: don't mess with courier or usher for now, but make sure chat-db and notif-db are in the realm desk.  Tome-db should stay separate, so it can be installed by any application.
