### ISSUE TITLE
Block concept spec

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#1223]
### Details
A block is a reusable data primitive that others can utilize on a common data layer. It may also have a UI component associated with it in the case of input or display. 

### Goals
To design a spec for the block concept and list out the various block types we would like to support in V1 and beyond.

### Todo
- [ ] Research: https://blockprotocol.org/hub
- [ ] List various blocks
- [ ] Design any components required for V1 block list
- [ ] Settle on a name for the concept
- [ ] Explore native-ui and card / widget system.
- [ ] Make issues attached to a new milestone

### Block list
- TODO
