### ISSUE TITLE
Build feature flag system into Realm

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#1227]
### Details
Feature flags will allow us to conditionally reveal features based on some permission

See: https://docs.launchdarkly.com/sdk/client-side/react/react-web

### Todo
- [ ] Integrate a feature flag SDK
- [x] Integrate new chat / old chat
- [ ] Document solution in wiki
