### ISSUE TITLE
New chat TODO list

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#1298]
### Bug list

- [ ] Double-send bug https://github.com/holium/realm/issues/1298#issuecomment-1497190056
- [x] Fix author label after a %status type. @drunkplato #1295 
- [x] Fix %reply crash bug @drunkplato #1295 
- [x] Emoji search input closes emoji picker @drunkplato #1302
- [x] If a new message comes in while you have a path actively open, should auto read the message notification. - @Tenari 
- [x] Make “add as friend” work in members list of ChatInfo - @leowini - #1300
- [x] Update the sentAt time via an interval similar to the clock  - @Tenari #1314 
   - [x] ChatLog - bubble footer #1314
   - [x] Inbox on ChatRow -> has preview #1314
   - [x] Day separator in old `apps/Messages` #1314 
- [x] onReply click event should navigate to row index of the original message. #1326 
- [x] Logout clears chat store (it does, but the avatars persist) - @drunkplato #1303
- [x] Grow ChatInput height when Shift + Enter (fix line-height) - @Tenari 
- [x] realm-chat should only create one notif per msg, not per msg-part - @Tenari 
- [x] Init the db before chat is needed -> notif updates and reconnecting - @drunkplato #1303
  - [x] Initial load has “Error loading title”
  - [x] Notifications need to get hydrated properly
- [x] update `lastTimeSent` in Chat Inbox when a message is sent or received. - @Tenari 
- [ ] `spaces.service.ts` password error should be wrapped in `development`
- [x] `overflowX='scroll'`: - @Tenari 
  - <img width="479" alt="image" src="https://user-images.githubusercontent.com/6413077/228610931-ce1fe818-7749-4561-a978-226796fc269c.png">
- [x] Consistent right click menu on `Bubble` components - @Tenari https://github.com/holium/realm/pull/1317
- [x] when you send me a message while I'm trying to pick an emoji react, it just disappears on me - #1302 fixed
- [x] fragment parser errors: - @Tenari 
  - [x] blockquote parser error <img width="395" alt="image" src="https://user-images.githubusercontent.com/3653835/228672720-76c172e2-9cf8-4324-addd-06ed4200587e.png">
  - [x] code block parser is adding newline <img width="407" alt="image" src="https://user-images.githubusercontent.com/3653835/228671903-5bf8a599-0dbd-4ea2-93fe-968615873a20.png">
- [x] angry crash when trying to paste an image from clipboard to upload to s3 - fixed #1302 
- [x] when replying to a longer message, the ui overflows badly - @Tenari 
  - <img width="445" alt="image" src="https://user-images.githubusercontent.com/3653835/228849644-73e35bd4-40fb-41f7-ad7b-b0c136af8219.png">
- [x] update bubble contents when editing - @drunkplato - #1311
- [x] Remove print statements in chat-db and notif-db, also remove dev-only code in on-load in realm-chat - @Tenari 
- [x] found chat crash when switching to chatDB chat from holium team chat on windows build ![image](https://user-images.githubusercontent.com/3653835/229170779-722729f2-8f9d-41b3-902b-062c5656dd4b.png)
- [ ] bulk load - @Tenari 
  - ![image](https://user-images.githubusercontent.com/3653835/229557355-1602df9e-31f1-48f6-9732-a05881edc7ec.png)
- [x] blockquote fragment parser with -> arrow. should restrict to beginning of line only - @Tenari https://github.com/holium/realm/pull/1318
  - ![image](https://user-images.githubusercontent.com/3653835/229558639-e82206fa-3216-4ba3-b74c-04ee64992553.png)
- [x] opengraph stuff - @Tenari  https://github.com/holium/realm/pull/1325
  - <img width="406" alt="image" src="https://user-images.githubusercontent.com/3653835/229857083-0874b627-b471-4e28-8afb-6722c105e035.png">

### Animation restructure
- [x] Fix initial animation expansion on Inbox @drunkplato - #1305
- [x] Private links (Ex. a Realm PR) attempt to render but don't - glitchy and leaves a bunch of empty space between messages.  

### New features - after stable
- [ ] Search improvement / search result with messages
- [ ] “save image” option on right click - @Tenari  https://github.com/holium/realm/pull/1327
- [ ] copy & paste on fragment text
- [x] clicking on an image should show it in a lightbox - @Tenari https://github.com/holium/realm/pull/1333
- [ ] Tooltip on ChatInfo icon uploader if you dont have S3 creds: "You don't have a storage bucket configured"
- [ ] One way migrate Groups -> metadata `source: 'groups' | 'talk' | 'chat'` flag in paths table
- [ ] `is typing...` data channel room for active chat log @leowini 
- [x] `%status` should be sent when the expiresDuration is changed. - @Tenari https://github.com/holium/realm/pull/1335

### After chat launch
- [ ] Bundle standalone chat app
