### ISSUE TITLE
DM attachments

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#133]
## Details

![Image](https://user-images.githubusercontent.com/6413077/196259464-2293e034-3fed-4645-8381-ef15b64544db.png)

Some of this integration was started but not finished.

## Tasks
- [ ] Get s3-store config state
- [ ] If s3-store is set, enable button, else show a tooltip on hover "No image store set up"
- [ ] Paste image, file, etc
- [ ] Attach via file browser without locking renderer
