### ISSUE TITLE
Chat BUGFIX - ROUND 1

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#1372]
### TODO
- [x] CRITICAL: if new messages are loading and one is a replyTo reference it could cause a crash (batch load new messages from the lastest scry)
- [x] `admin` members aren't added to the chat in the init and creation of a space chat in `%spaces-chat`. Cody was an admin of `realm-forerunners` and actually did not have a `member` role so he wasn't auto-added.
- [x] Editing doesn't load the message anymore @drunkplato broke
- [x] Disappearing messages while in the chat log crashes
- [x] #1366 https://github.com/holium/realm/pull/1433
- [x] Soundcloud should load in react-player, but doesn't -- https://github.com/holium/realm/pull/1468
- [x] Add emoji icon and picker next to the attachments icon in `ChatInput` for sending emoji -- https://github.com/holium/realm/pull/1461
- [x] Right click on image and "Copy image link"
- [x] Right click on text "Copy" 
- [x] Right click on links "Copy link"
- [x] #1374 https://github.com/holium/realm/pull/1416
- [x] Video files fail to upload properly as well ^  https://github.com/holium/realm/pull/1416
- [x] ChatInbox doesn't reorder the list with `updatedAt` when new messages come in https://github.com/holium/realm/pull/1465
- [ ] Find a way to actually premeasure TweetBlocks height prior to sending (measureTweet function already in TweetBlock folder)
- [x] Give both peers of type DM chat the ability to modify ChatInfo settings https://github.com/holium/realm/pull/1421
- [x] NewChat page sigil is not full height
  - <img width="463" alt="image" src="https://user-images.githubusercontent.com/6413077/231155759-f0447cd6-cc37-462f-978d-ed2a135ec475.png">
- [x]  ChatRow lastMessage preview
  - [x] Remove "break" from the ChatRow lastMessage preview
  - [x] Render URLs as strings
- [x] Reply and pinned messages only take first fragment (that along with ChatRow preview) should use the same logic for generating string only versions of fragments https://github.com/holium/realm/pull/1452
- [x] Deleting a chat should delete the notifications (or dismiss them) for that path https://github.com/holium/realm/pull/1466
- [x] Properly grow the row height when an emoji reaction is added. If you are at the bottom it pushes down rather than pushing up. -- https://github.com/holium/realm/pull/1471
- [ ] Get Sentry source maps connected to production releases
