### ISSUE TITLE
Port wallet logic to os-refactor structure

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#1411]
### Details
In order to launch the new hosted onboarding flow, we need to port all app logic over to the new structure. This heavily simplifies the app logic and will make bug fixes easier.

The most up to date branch with new rebuild logic is `rebuilt-os-process-apps`

### TODO
- [ ] Meet with @drunkplato to go over the new structure
- [ ] `%realm-wallet` should persist transaction history and other wallet data in the `<ship-name>.sqlite` database
  - [ ] post the schema in this issue before moving forward
- [ ] Move most of the wallet logic in the os folder into a lib in the renderer. Aim for the "@holium/wallet" lib goal we had back in November. The os process should only pull data down into the db and poke out to the agents.
