### ISSUE TITLE
Rebuild TODO

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#1481]
### Details

This is a holding issue for all the small issues and tweaks we have to fix in the Realm rebuild. 

#### Onboarding
- [x] Adding a ship isn't immediately reflected https://github.com/holium/realm/pull/1495
- [x] Third Earth ships get stuck on the passport step now https://github.com/holium/realm/pull/1493
- [ ] Uncomment encryption of ship DB and make sure it's encrypted/decrypted correctly @gdbroman 
- [x] Splash screen shows on every dev save https://github.com/holium/realm/pull/1499
- [x] Add new account management handling in settings https://github.com/holium/realm/pull/1493
- [x] Install Realm doesn't wait for installation to finish https://github.com/holium/realm/pull/1493
- [x] Test in prod 28/4 (client + web) @gdbroman

#### Chat
- [x] Reply to is not working https://github.com/holium/realm/pull/1490
- [x] ChatInput seems a bit taller (fatter) than before. #1483
- [x] `api.holium.live` in header #1483
- [x] Fix live updates #1483
- [x] replyTo doesnt push up the list when ChatInput has the reply element visible https://github.com/holium/realm/pull/1499
- [ ] DOMException: No valid data on clipboard. when pasting an image copied from iPhone - make issue for next week

#### App install
- [x] Popover is not working, flickers and disappears. @lodlev-migdev #1497 
- [x] Force Realm install (onboarding) to wait for installation to complete @lodlev-migdev #1503 

#### Components
- [x] InlineEdit needs to be ported to `lib/design-system` and placed back in `ChatInfo` https://github.com/holium/realm/pull/1496

#### Wallet
- [x] Merge it first

#### Rooms - @drunkplato is working on this
- [x] Doesnt auto open room view on create
- [x] Doesnt remove room from tray when left
- [ ] Test it all really...

#### Misc
- [x] Power Off button logs you out https://github.com/holium/realm/pull/1496
- [x] Pinned app reorder @lodlev-migdev #1497 
- [x] ConnectionStatus component setup
- [x] Window cookie refresh fires too many events (slows down) -- https://github.com/holium/realm/pull/1499
  - <img width="477" alt="image" src="https://user-images.githubusercontent.com/6413077/234411931-d4c5b18d-2eac-4f82-8995-c6fc41a4aa04.png">
