### ISSUE TITLE
rooms V2

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#214]
## Details
The rooms lib needs a cleanup to allow for easy cursor streaming, we need to port over the multiplayer cursor lib to work with data channels. There are several UX questions that also need to be answered around window position and the developer experience of using cursors.

## Developer SDK
A developer should be able to install the `@holium/realm-multiplayer` and `@holium/room` lib in JS and expect that if they have a cookie set with the `urbauth~zod` key, the lib will pull room state from the %room agent and try to initiate connections. The lib must make it easy to stream any data through data channels using the `RemoteParticipant` object. 

Once the lib is built out, it will need to be extensively documented.

## Useful links
- [ ] https://github.com/webrtc/samples/tree/gh-pages/src/content/peerconnection

## Tasks
- [x] Design the API for the `@holium/room` lib.
- [ ] Implement an updated `@holium/room` lib.
  - [ ] Detect mic source changes
  - [x] Test protocol
  - [x] Muting & unmuting
  - [ ] Speaking & not speaking
- [x] Updated rooms agent 
- [x] Room protocol

## Break into new issue
- [ ] Update `@holium/realm-multiplayer` lib to work with rooms.
- [ ] Add ability to use star-paired LiveRoom server. (break out into separate issue)
