### ISSUE TITLE
Add erc-20 coins to the ethereum wallet

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#217]
## Design
![Image](https://user-images.githubusercontent.com/6413077/193023026-26839182-a257-4c20-b747-6e34e00ed9f6.png)

- https://www.figma.com/file/fLyHeds19uXjvoDL1Z3zCF/Realm-Core?node-id=2206%3A13517

## Tasks
- [ ] implement tabbed list
- [ ] implement coin list
- [ ] implement coin detail
- [ ] retrieve coin balances
- [ ] retrieve coin images
