### ISSUE TITLE
Add erc-721 NFTs to the ethereum wallet

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#218]
## Design
![Image](https://user-images.githubusercontent.com/6413077/193022696-82d66680-6cf7-435b-b938-e00c701eef7c.png)

- https://www.figma.com/file/fLyHeds19uXjvoDL1Z3zCF/Realm-Core?node-id=2206%3A13517

## Details
Floor price is not required for this issue to be completed. I will add it as an additional issue.

## Tasks
- [ ] implement nft list
- [ ] implement nft detail
- [ ] retrieve nft metadata
- [ ] retrieve nft images
