### ISSUE TITLE
ContextMenu on SpaceRow should say "Leave" if not owner

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#232]
## Tasks

- [x] If you are the owner, show delete
- [x] If deleting, show confirm dialog 
  - [x] build a general "confirm dialog" component (should have confirm in red and close)

## Dialog design

This image is the wallpaper dialog, but the confirm dialog would be similar with a few tweaks.
The buttons at the bottom should be "Cancel" in neutral or "Confirm" in red. 
Instead of the wallpaper selector the dialog should have a title and description prop that could be passed in. 

![Image](https://user-images.githubusercontent.com/6413077/199220602-6fc35645-92ad-4bc1-b594-1d9ca3e7f460.png)
