### ISSUE TITLE
%spaces - groups 2 integration

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#247]
## Details

Right now there is no integration with spaces and new groups.

It simply fetches a list of your hosted groups from old `%group-store`.

![Image](https://user-images.githubusercontent.com/6413077/199223292-56d3ddfb-7ff3-4bda-9e57-cd65bcfa3515.png)

## Tasks

- [x] Update spaces creation workflow to pull member list from groups 2 and populate on the member add step.
  - [x] Map permissions from groups 2 to space members 
- [x] Update the groups scry to fetch from groups 2.
- [x] Pull group image and name into the Edit Details step if you "Add space" to a group.

## Next tasks

After the first two tasks are down, we should discuss syncing spaces and group member lists if someone creates a space that is of type `%group`.
