### ISSUE TITLE
Confirm friends invite flow works in %our space

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#281]
## Tasks

![Image](https://user-images.githubusercontent.com/6413077/199219796-a9522121-eb80-4db8-a5ea-10cc70413bfc.png)

- [x] I can invite and remove a friend from the friends list in `%our` space.
- [x] Remove error state on input 
- [x] Clicking enter or clicking (once) on the row element should add the friend
- [ ] Think about UI element to articulate mutually added friends
