### ISSUE TITLE
Cookie overhaul

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#284]
## Details

Right now the auth cookies are stored in plaintext in `realm.auth.json`. We need to refactor this to be stored in the ship subfolder.

## Tasks
- [ ] Refactor onboarding to store initial cookie in ship subfolder
- [ ] Make a cookie manager (js class) that can be used in the `auth.service.ts` file
- [ ] It should be able to use the `set-cookie` header from conduit to update the cookie. 
- [ ] It should keep track of if a cookie is valid and prompt to fetch a new cookie if the old one is invalid.
