### ISSUE TITLE
Handle public space joining

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#301]
## Tasks
- [x] Update %spaces agent to support public spaces (there are some TODOs in there mentioning it)
- [x] Add search toggle to Spaces tray
- [ ] Confirm join workflow works 

![Image](https://user-images.githubusercontent.com/6413077/200324253-71b12f75-2c69-40c0-a7ea-5433719080e4.png)

## Future issue
We need to host a featured spaces list somewhere (`~hostyv`)
- [ ] Simple agent that can store multiple "featured" lists.  
  - [ ] Featured spaces
  - [ ] Featured apps
