### ISSUE TITLE
Render efficiency check

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#372]
This is a loose issue in that the goal is to go through each component that builds up the OS interface and find unnecessary re-rendering and assess each case.

## Task
- [ ] Determine a strategy for measuring performance.
- [ ] Go through each component that is relevant and note which have too many unnecessary re-renders. Note them in this issue as a comment.
- [ ] Fix components with useMemo or other strategies.
