### ISSUE TITLE
Polish group dm ui

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#373]
## Details 

There are a few polish tasks to get the mobile app and dm tray app visually in sync.

<img src="https://user-images.githubusercontent.com/6413077/204783224-caf9e457-ed80-4e28-a00a-c90a36c8a4eb.png" alt="realm image" height="500px"/>

## Tasks
- [ ] Add ellipsis to the group dm header title
- [ ] Add participant count as subtitle (see mobile app image below)
- [ ] Stack same patp messages (see mobile app image below)

<img src="https://user-images.githubusercontent.com/6413077/204783516-979a29d5-b500-43e3-b327-d5be3d45c06e.png" alt="mobile image" height="500px"/>
