### ISSUE TITLE
Design and implement friend states

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#375]
## Details

The %friends agent has a concept of `follower`, `following`, or `fren`.

Based on each of these, we should indicate in the UI which status the friend is. 

If follower, allow the user to choose "Add as friend", which will then mutually add and change the status to `fren`.

If following, allow users to "unfollow". 

## Tasks
- [ ] Design follower state
- [ ] Design fren state
- [ ] Design following state
- [ ] Implement all designs
