### ISSUE TITLE
Polish chat log

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#407]
## Details
After merging the list component, I noticed some of the content types still have height issues. We should go through each content type and make sure they all work properly.

Note: After the initial load, the next time the element mounted it properly set the height.

## Content types
- text
- url
- mention
- code
- reference

## Tasks
- [ ] Faded state doesn't re-render on success. 
- [ ] Initial message fetch may trigger "No messages" instead of showing the newly fetched messages.
- [ ] Upload status indicator (if an image upload is happening, we should put in a loader element in the chat log)
- [ ] Get query s3-store on dm tray app open, not chat log open. 
- [ ] Handle failed images with error image placeholder (Trent to design -- but it will be a grey box with ! in the center)
- [ ] New dm has a blank bubble after sending first message

![Image](https://user-images.githubusercontent.com/6413077/206701627-752ff7aa-5be0-4b65-ae7f-b2ad55d8b8fe.png)
