### ISSUE TITLE
Reorder AppGrid

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#408]
## Details

We need to be able to click and hold and rearrange tiles on the AppGrid. There is a map stored in bazaar called `grid-index` that can be updated based on the reorder logic of the UI. 

### Realm support issue
- https://github.com/holium/realm-support/issues/14

## Tasks

- [x] Add click + hold state to tile (accent colored focus outline)
- [x] Drag to reorder the `grid-index` (see framer-motion reorder)
- [x] Persists reordered `grid-index` map properly.
