### ISSUE TITLE
suspended state for app tiles

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#417]
## Details 

If an app is suspended it triggers the loading state. We need to expand the logic to account for other `installStatus` values.

![Image](https://user-images.githubusercontent.com/6413077/206224547-70f25ac3-d131-49d2-8881-7ebe42ca99f8.png)

## Tasks
- [ ] Design suspended state @drunkplato 
- [ ] Implement suspended state design
- [ ] add to context-menu and show `Suspend App` and `Resume App` depending on state.
