### ISSUE TITLE
%bazaar maintenance pokes

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#509]
## Details

We need maintenance pokes to cleanup and help users recover from issues.

## Tasks

Make sure all of these pokes are properly permissioned.

- [ ] `[%rebuild-catalog ~]` - simply rebuilds the catalog and doesn't clear out your recommended list or stalls
- [ ] `[%rebuild-stall =space-path]` - will request the catalog apps needed for a stall (recommended and app suite) from the host of the space
- [ ] `[%clear-stall =space-path]` - will delete the stall as a host and send updates to all members to also clear that stall
