### ISSUE TITLE
Style "<ship> joined the chat"

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#546]
### Details

We need to find a way to style this - perhaps in the same way that the date divider is formatted.

![Image](https://user-images.githubusercontent.com/6413077/207712505-b2f218ed-4da9-4b91-9841-072778dbe67b.png)

### Tasks

- [ ] Design "joined the chat" ui element - @drunkplato 
- [ ] Make any changes in courier to more support that feature
- [ ] Implement UI parser.
