### ISSUE TITLE
Notification system - beacon + local notification settings

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#551]
### Details

We need a more elegant strategy for managing notifications and unread counts throughout Realm. 

### Tasks

Can break this down in two PRs:
1. Design system components PR into master
2. `notification.service.ts` integration PR into master

#### Design
- [x] Design notifications UI
- [x] Design toast component
- [x] Design settings pane for notification settings

#### UI
- [x] Build toast component
  - [ ] Wallet
  - [ ] Chat
  - [ ] Generic 
- [x] Build notification components w/ storybook
  - [x] App grouped
    - [ ] Racket integration
  - [x] App & path grouped
    - [x]  Chat integration

#### Backend
- [x] Add schema to `init.sql`
- [x] Fetch with timestamp
- [x] Make any agent changes required
- [x] Integrate notif-db into the SQLite db using a new `notification.service.ts`
  - [x] Get unreads from SQL query
  - [x] Provide `readNotification` action from service that takes app, and an optional path 
  - [x] Provide `dismissNotification` action from service that takes app, and an optional path 

#### Notification tray
Link: https://www.figma.com/file/3NMAfjSUcuJ9TasiLwocNt/Realm-2023?node-id=1920%3A19393&t=y6tyhD19jPGgzUUm-4
![image](https://user-images.githubusercontent.com/6413077/225063673-f0a7064e-9971-40ed-b0b8-f2488a1b3a76.png)

#### Toast
Link: https://www.figma.com/file/3NMAfjSUcuJ9TasiLwocNt/Realm-2023?node-id=2003%3A15765&t=y6tyhD19jPGgzUUm-4
![image](https://user-images.githubusercontent.com/6413077/225063197-a527670e-1043-42b9-b705-35918971b0bc.png)

#### Settings
Link: https://www.figma.com/file/3NMAfjSUcuJ9TasiLwocNt/Realm-2023?node-id=2007%3A16969&t=y6tyhD19jPGgzUUm-4

![Image](https://user-images.githubusercontent.com/6413077/225091131-6e3eb6f0-59eb-4982-8c32-e46e205cc738.png)
