### ISSUE TITLE
Add ability to manage roles in MemberList as an admin

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#570]
### Details

We currently have no way to change roles or promote to admin once the space is created. So we need to add a context menu option for "Manage role" in the context menu for the MemberList row.

### Tasks
- [x] Design dialog for managing roles.
- [x] Add role to passport card only in MemberList.
- [x] Verify role changes propagate to Groups and vice-versa
