### ISSUE TITLE
Add announcements widget to spaces

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#571]
### Details

We need a way to post updates or status messages in the Spaces home page. The idea is to allow admins to edit a "bulletin" block that is at the top of the Spaces home page. 

### Tasks
- [x] Design bulletin box
- [ ] Design admin ui
- [ ] Implement changes in the `bulletin` agent to store new data for space specific bulletins without wiping state.
- [ ] Add admin ui to manage announcements
- [ ] Should be able to input the title and body (simple text for v1)
- [ ] Should be able to set the color in admin ui (generate the values using polished)
- [ ] Test that updates are sent in real-time.

### Design
https://www.figma.com/file/3NMAfjSUcuJ9TasiLwocNt/Realm-2023?node-id=163%3A2684&t=8AmFzpKnUPuMVOSp-4

![Image](https://user-images.githubusercontent.com/6413077/211040476-ae8da794-675b-4956-922d-614e5d473a0b.png)
