### ISSUE TITLE
Notification dot on rooms chat icon

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#573]
### Details

There is no indication in the UI that a new Rooms chat has been received. This prevents people from using the chat.

### Tasks
- [ ] Add `minimal` Badge to chat icon in Rooms
- [ ] Keep track of "unread" messages in local state. 
- [ ] Clear "unread" count when clicking on chat icon.
