### ISSUE TITLE
Create an avatar upload component

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#584]
### Details

We currently have various areas where the profile avatar is set, but it needs to be unified in a single component. 

### Tasks
- [ ] Look at `ProfileSetup.dialog.tsx` and `Account.tsx` (under settings) and utilize the same component.
- [ ] Build a `SigilUpload` component in `@holium/design-system` with story.
- [ ] Replace current code with `SigilUpload`.

### Future work
- Do the same with `Crest` + `CrestUpload` for Spaces.
