### ISSUE TITLE
Hosting flow: Booting

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#59]
![image](https://user-images.githubusercontent.com/6413077/174668598-90eb9d9e-3a3a-4bba-ad82-ecfc1eaec165.png)

- [Figma link](https://www.figma.com/file/fLyHeds19uXjvoDL1Z3zCF/Realm-Core?node-id=149%3A6026) 

### Tasks
- [ ] Poll third earth status endpoint for completion
- [ ] Load ship metadata (`patp`, `url`, `access code`) into the ShipManager in `realm.core`
- [ ] Redirect to profile on `next()`
