### ISSUE TITLE
Rooms: test suite

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#671]
### Details

We need to write tests for the rooms lib that can simulate the various test cases.

Will require R&D to determine how to automate

### Tasks
- [ ] Write tests to simulate functionality
- [ ] Add test script to package.json
- [x] Also should do this: [#649](https://github.com/holium/realm/issues/649)
