### ISSUE TITLE
Contact sharing (realm)

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#941]
### Details
We need to share contacts without relying on `landscape`. 

Check out this branch `941-contact-sharing-realm` and make a draft PR. 

### Tasks
- [x] Update and merge PR 422: https://github.com/holium/realm/pull/422
  - [x] Adding a friend instantly shares contact info and should update the UI
  - [x] Write migration from current friends state to a new `state-1` in `on-load`, no autonuke.
  - [x] Joining a space should start a thread that will share contact info with all of the users in the space. 
  - [x] When someone joins a space and they share their contact, respond with your current metadata
  - [x] When you update your avatar, it should update all ships in `%friends`
  - [x] Add setting in `%friends` agent that enables and disables sync with `%contact-store`, default is off.
 - [x] Remove contact model from `/os` and replace with `friends`. 
 - [x] Replace all Sigil component usage with the new `Avatar` component in `@holium/design-system`
 - [x] Add fallback image logic to `Avatar` - should fallback to the sigil of the avatar img url fails to load.
   - See the Crest upload for how failing images are handled. There or the Spaces detail edit modal. 
 - [x] Any update to avatar should also update `realm.auth.json` metadata.
