### ISSUE TITLE
Wallet UX improvements

### ISSUE THREAD

**Issue by drunkplato** [holium/realm#942]
### Tasks
- [ ] Estimate gas fees
- [ ] Derive address at path input (advanced)
- [ ] Bundle `on-demand` addresses (design) 
- [ ] Add ability to remove addresses from the list
- [ ] Add ability to hide/unhide addresses
